services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: im_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "imchat"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  # Redis 缓存
  redis:
    image: redis:7.0-alpine
    container_name: im_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  # Kafka 服务
  kafka:
    image: apache/kafka:3.7.0
    container_name: im_kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      # 节点角色和 ID
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      # 监听配置：9092 对外提供服务，9093 用于内部控制
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # 自动创建 Topic
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    volumes:
      - ./data/kafka:/var/lib/kafka/data